### PR TITLE
Upgrade to spigot 1.11

### PR DESCRIPTION
**Pull request by Aleksey-Terzi**

### CODE REVIEW

**Comment by ProgrammerDan** [comment]
This is a huge body of work; we don't generally maintain CTP however beyond some fixes and alterations to suite our needs.

How much does your update diverge from mainline here: https://github.com/MinelinkNetwork/CombatTagPlus ?

Thanks for pushing this update through. Depending on what you find, we might just go with your PR instead of following mainline, although that saddles us with a new maintenance problem moving forward. 

Thoughts?

**Comment by Aleksey-Terzi** [comment]
Mainline is already supporting 1.11 and they did a lot of work.
Not sure what exactly changes were done here, but probably would be good idea to merge with their source and update if this will be needed.

Therefore I propose to discard my current changes and merge DevotedMC's fork with MinelinkNetwork.

**Comment by Aleksey-Terzi** [comment]
What is your opinion?
Are you agree if I will try to merge Devoted's changes with MinelinkNetwork and then make new pull request?

**Comment by ProgrammerDan** [comment]
I apologize, I forgot to respond. Yes, we should probably merge in Minelink's. I think the biggest difference is that Minelink added a bit of code to uncombattag on plugin teleport, this wasn't usable for our case. However, they merged in my fixcode to make it configurable so we should be good with mainline.

**Comment by Aleksey-Terzi** [comment]
Ok, thanks for confirmation.

>  I think the biggest difference is that Minelink added a bit of code to uncombattag on plugin teleport, this wasn't usable for our case. 

Ok, I will look this during testing.

**Pull request closed without merging**
